---
- name: Restart auditd service
  service:
    name: auditd
    state: restarted
  become: true

- name: Generate auditd rules
  command: augenrules --load
  notify: Restart auditd service
  become: true
